name: Continuous Integration
on: [push, pull_request]
jobs:
  test:
    name: "Test #${{ matrix.flavor }}: node v${{ matrix.node }}, ${{ matrix.typescript }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        flavor: [1, 2, 3, 4, 5, 6, 7, 8, 9]
        include:
          - flavor: 1
            node: 6
            typescript: typescript@latest
          - flavor: 2
            node: 12.15
            typescript: typescript@latest
          - flavor: 3
            node: 12.16
            typescript: typescript@latest
          - flavor: 4
            node: 13
            typescript: typescript@latest
          - flavor: 5
            node: 13
            typescript: typescript@2.7
          - flavor: 6
            node: 13
            typescript: typescript@next
          - flavor: 7
            node: 14
            typescript: typescript@latest
          - flavor: 8
            node: 14
            typescript: typescript@2.7
          - flavor: 9
            node: 14
            typescript: typescript@next
    steps:
      # checkout code
      - uses: actions/checkout@v2
      # install node
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      # lint, build, test
      - run: npm install
      - run: npm run build
      - run: npm rm tslint
      - run: npm install ${{ matrix.typescript }}
      - run: npm run test-cov
